### ISSUE TITLE
ERROR: Unable to find 'corrade/2020.06@helmesjo/stable' in remotes

### ISSUE THREAD

**Issue by mscofield0** [helmesjo/conan-corrade#2]
I'm getting the above error when trying to install Corrade via `conan install corrade/2020.06@helmesjo/stable`

**Comment by helmesjo** [comment]
Hi! Yes, this package is not available in my new artifactory repo (bintray has been shutdown so had to change).
Are you using only this package? Because it is already available in the official "conan-center" repository. Just search using `conan search corrade -r conan-center` and you'll find it there: `corrade/2020.06`.

**Comment by mscofield0** [comment]
I am using Magnum and that is its dependency so I had to require that too (unless I'm understanding the error messages wrong lol, new to Conan)

**Comment by mscofield0** [comment]
I will try to include it from the `conan-center` repo, thanks
